# Generated by Django 4.1.7 on 2023-03-15 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.IntegerField()),
                ('wall', models.IntegerField()),
                ('mine', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('fountain', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('farm', models.IntegerField()),
                ('food', models.IntegerField()),
                ('cov_tower', models.IntegerField()),
                ('cov_resources', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player2State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.IntegerField()),
                ('wall', models.IntegerField()),
                ('mine', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('fountain', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('farm', models.IntegerField()),
                ('food', models.IntegerField()),
                ('card1', models.IntegerField()),
                ('card2', models.IntegerField()),
                ('card3', models.IntegerField()),
                ('card4', models.IntegerField()),
                ('card5', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player1State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower', models.IntegerField()),
                ('wall', models.IntegerField()),
                ('mine', models.IntegerField()),
                ('gold', models.IntegerField()),
                ('fountain', models.IntegerField()),
                ('mana', models.IntegerField()),
                ('farm', models.IntegerField()),
                ('food', models.IntegerField()),
                ('card1', models.IntegerField()),
                ('card2', models.IntegerField()),
                ('card3', models.IntegerField()),
                ('card4', models.IntegerField()),
                ('card5', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_card', models.IntegerField(null=True)),
                ('second_last_card', models.IntegerField(null=True)),
                ('initial_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.initialstate')),
                ('player1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainapp.player1state')),
                ('player2', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.player2state')),
            ],
        ),
        migrations.CreateModel(
            name='HumanPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_count', models.IntegerField(default=0)),
                ('initial_states', models.ManyToManyField(to='mainapp.initialstate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
