# Generated by Django 4.1.7 on 2023-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstate',
            name='last_card',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')], null=True),
        ),
        migrations.AlterField(
            model_name='matchstate',
            name='second_last_card',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')], null=True),
        ),
        migrations.AlterField(
            model_name='player1state',
            name='card1',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player1state',
            name='card2',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player1state',
            name='card3',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player1state',
            name='card4',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player1state',
            name='card5',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player2state',
            name='card1',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player2state',
            name='card2',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player2state',
            name='card3',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player2state',
            name='card4',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
        migrations.AlterField(
            model_name='player2state',
            name='card5',
            field=models.IntegerField(choices=[(1, 'Tiny mouse'), (2, 'Arcane Butterfly'), (3, 'Feline Familiar'), (4, 'Foam Reptile'), (5, 'Loyal Mount'), (6, 'Common wolf'), (7, 'Werewolf'), (8, 'Dwarves'), (9, 'Mermaid'), (10, 'Orcs'), (11, 'Friendly Fairy')]),
        ),
    ]
