# Generated by Django 4.1.7 on 2023-03-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_matchstate_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchstate',
            name='player1',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.player1state'),
        ),
        migrations.AlterField(
            model_name='matchstate',
            name='player2',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.player2state'),
        ),
    ]
